### ISSUE TITLE
Concat vars in include

### ISSUE THREAD

**Issue by ensk** [pattern-lab/edition-php-twig-standard#2]
whe use <code>{% include 'molecules-' ~ view.item ~ '-' ~ view.mode %}</code> and generate patternlab the console show a warning  <code>{> molecules- }} is not a valid pattern...</code> but the pattern is printed normally

**Comment by dmolsen** [comment]
@ensk -

The warning happens when Pattern Lab is trying to build lineages. Lineages are used in the code view modal when it says "this pattern contains...". You can safely ignore the warning since you're essentially working around that feature by making the pattern inclusion dynamic.

**Comment by TxHawks** [comment]
@ensk -
I'm not next to a computer, so can't test this right now, but one possible way to not break lineages is using interpolation or a variable:

``` twig
{# Interpolation method #}
{# Note that you need to use "s rather than 's to wrap your string for interpolation to work #}
{% include "molecules-#{view.item}-#{view.mode}" %}
```

``` twig
{# Variable method #}
{%- set my_pattern = 'molecules-' ~ view.item ~ '-' ~ view.mode -%}
{% include my_pattern %}
```

If the above doesn't work, and you don't care about lineages but want to get rid of the error message, for the time being, you can try the `include` function instead of the `include` tag:

``` twig
{{ include('molecules-' ~ view.item ~ '-' ~ view.mode) }} 
```

Until pattern-lab/edition-php-twig-development#15 is fixed, the `include` function isn't taken into account when building lineages. This, obviously, isn't future proof, as the bug will probably be fixed at some point, but at worst you will be at the same place you are at now. 

At any rate, I do believe my first suggestion should work, and then you get both lineage and no error message.
